version: "3.8"

networks:
    network:
        driver: bridge

volumes:
    database:

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - network
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./backend:/var/www/html
        networks:
            - network
        depends_on:
            - mysql

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
        networks:
            - network
        depends_on:
            - backend

    mysql:
        image: mysql:8.3.0
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "restaurant"
        ports:
            - "3306:3306"
        volumes:
            - "database:/var/lib/mysql"
        networks:
            - network
